// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyglvihduuiboautagff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Z2x2aWhkdXVpYm9hdXRhZ2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTI0NzAsImV4cCI6MjA2NDgyODQ3MH0.r-2cvSxA-aCtuaZIEYkOmnzzfyaMA04-2ntiGAwu9Jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);